<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>E-learni live classes</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
</head>
<body>

    <div id="intro-container">
        <h2><img src="../assets/images/logo.png" style="height: 40px;" alt=""></h2>


    <div id="videos">
        <video class="video-player" style="width: 100px; margin-left: -200px; "id="user-1" autoplay playsinline></video>
        <video class="video-player" style="width: 1000px; margin-left: -100px;"  id="user-2" autoplay playsinline></video>
    </div>

    <div class="step">
        <p><strong>Step 1:</strong> User 1,  click "Create offer" to generate Sequred Id and copy offer from text area below.</p> <br>

        <button style="border-radius: 700px 20px 70px 30px; background-color:aqua; padding:10px; padding-left:20px;"  id="create-offer">Create Sequred Id</button>
    </div>

    <label>Sequred Id:</label>
    <textarea id="offer-sdp" placeholder='User 2, paste Sequred Id here...'></textarea>

    <div class="step">
        <p><strong>Step 2:</strong> User 2, paste Sequred Id generated by user 1 into text area above, then  click "Create Answer" to generate Sequred Id Answer and copy the answer from the text area below.</p> </br>
        <button style="border-radius: 700px 20px 70px 30px; background-color:aqua; padding:10px; padding-left:20px;" id="create-answer">Create Sequred Id</button>
    </div>


    <label>Sequred Id Answer:</label>
    <textarea id="answer-sdp" placeholder="User 1, paste Sequred Id Answer here..."></textarea>

    <div class="step">
        <p><strong>Step 3:</strong> User 1, paste Sequred Id generated by user 2 into text area above and then click "Add Answer"</p> </br>
        <button style="border-radius: 700px 20px 70px 30px; background-color:aqua; padding:10px; padding-left:20px;"  id="add-answer">Add answer</button>
    </div>

</body>
<script src='main.js'></script>
</html>